<?php

use Illuminate\Database\Seeder;

class InformeTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('informe')->delete();
        
        \DB::table('informe')->insert(array (
            0 => 
            array (
                'id' => 1,
                'idinforme' => '1',
                'url_informe' => 'https://uca.edu.sv/iudop/wp-content/uploads/informe1n-1.pdf',
                'titulo' => 'El pueblo salvadoreño ante el diálogo',
                'fecha_inicio' => '1986-09-04',
                'fecha_fin' => '1986-09-04',
                'tipo_informe' => 1,
                'eliminado' => 0,
                'idusuario' => NULL,
                'created_at' => '2021-07-07 05:02:57',
                'updated_at' => '2021-07-07 05:02:57',
            ),
            1 => 
            array (
                'id' => 2,
                'idinforme' => '2',
                'url_informe' => 'https://uca.edu.sv/iudop/wp-content/uploads/informe2.pdf',
                'titulo' => 'El pueblo salvadoreño ante el diálogo II',
                'fecha_inicio' => '1986-09-22',
                'fecha_fin' => '1986-09-22',
                'tipo_informe' => 1,
                'eliminado' => 0,
                'idusuario' => NULL,
                'created_at' => '2021-07-07 05:02:57',
                'updated_at' => '2021-07-07 05:02:57',
            ),
            2 => 
            array (
                'id' => 3,
                'idinforme' => '3',
                'url_informe' => 'https://uca.edu.sv/iudop/wp-content/uploads/informe31-1.pdf',
                'titulo' => 'El transporte colectivo en el área metropolitana de San Salvador',
                'fecha_inicio' => '1986-12-15',
                'fecha_fin' => '1986-12-15',
                'tipo_informe' => 2,
                'eliminado' => 0,
                'idusuario' => NULL,
                'created_at' => '2021-07-07 05:02:57',
                'updated_at' => '2021-07-07 05:02:57',
            ),
            3 => 
            array (
                'id' => 4,
                'idinforme' => '4',
                'url_informe' => 'https://uca.edu.sv/iudop/wp-content/uploads/informe41.pdf',
                'titulo' => 'El Salvador a fines de 1986',
                'fecha_inicio' => '1986-03-19',
                'fecha_fin' => '1986-03-19',
                'tipo_informe' => 3,
                'eliminado' => 0,
                'idusuario' => NULL,
                'created_at' => '2021-07-07 05:02:57',
                'updated_at' => '2021-07-07 05:02:57',
            ),
            4 => 
            array (
                'id' => 5,
                'idinforme' => '5',
                'url_informe' => 'https://uca.edu.sv/iudop/wp-content/uploads/informe5.pdf',
                'titulo' => 'El Gobierno en cuestión : Opiniones sobre las políticas gubernamentales y las acciones del sector empresarial',
                'fecha_inicio' => '1987-03-26',
                'fecha_fin' => '1987-03-26',
                'tipo_informe' => 2,
                'eliminado' => 0,
                'idusuario' => NULL,
                'created_at' => '2021-07-07 05:02:57',
                'updated_at' => '2021-07-07 05:02:57',
            ),
            5 => 
            array (
                'id' => 6,
                'idinforme' => '6',
                'url_informe' => 'https://uca.edu.sv/iudop/wp-content/uploads/La-educacion-El-Salvador-N%C2%B06-1987.pdf',
            'titulo' => 'La Educación en El Salvador (25 de mayo de 1987)',
                'fecha_inicio' => '1987-05-25',
                'fecha_fin' => '1987-05-25',
                'tipo_informe' => 2,
                'eliminado' => 0,
                'idusuario' => NULL,
                'created_at' => '2021-07-07 05:02:57',
                'updated_at' => '2021-07-07 05:02:57',
            ),
            6 => 
            array (
                'id' => 7,
                'idinforme' => '7',
                'url_informe' => 'https://uca.edu.sv/iudop/wp-content/uploads/informe71-1.pdf',
                'titulo' => 'Opiniones sobre las políticas gubernamentales y el incremento de movilizaciones populares de protesta',
                'fecha_inicio' => '1987-07-09',
                'fecha_fin' => '1987-07-09',
                'tipo_informe' => 2,
                'eliminado' => 0,
                'idusuario' => NULL,
                'created_at' => '2021-07-07 05:02:57',
                'updated_at' => '2021-07-07 05:02:57',
            ),
            7 => 
            array (
                'id' => 8,
                'idinforme' => '8',
                'url_informe' => 'https://uca.edu.sv/iudop/wp-content/uploads/informe81-1.pdf',
                'titulo' => 'La situación de la salud en El Salvador, 1987',
                'fecha_inicio' => '1987-07-24',
                'fecha_fin' => '1987-07-24',
                'tipo_informe' => 2,
                'eliminado' => 0,
                'idusuario' => NULL,
                'created_at' => '2021-07-07 05:02:57',
                'updated_at' => '2021-07-07 05:02:57',
            ),
            8 => 
            array (
                'id' => 9,
                'idinforme' => '9',
                'url_informe' => 'https://uca.edu.sv/iudop/wp-content/uploads/informe9.pdf',
                'titulo' => 'Las movilizaciones populares de protesta en San Salvador',
                'fecha_inicio' => '1987-08-31',
                'fecha_fin' => '1987-08-31',
                'tipo_informe' => 2,
                'eliminado' => 0,
                'idusuario' => NULL,
                'created_at' => '2021-07-07 05:02:57',
                'updated_at' => '2021-07-07 05:02:57',
            ),
            9 => 
            array (
                'id' => 10,
                'idinforme' => '10',
                'url_informe' => 'https://uca.edu.sv/iudop/wp-content/uploads/informe10.pdf',
                'titulo' => 'Los salvadoreños ante Esquipulas II',
                'fecha_inicio' => '1987-10-21',
                'fecha_fin' => '1987-10-21',
                'tipo_informe' => 1,
                'eliminado' => 0,
                'idusuario' => NULL,
                'created_at' => '2021-07-07 05:02:57',
                'updated_at' => '2021-07-07 05:02:57',
            ),
            10 => 
            array (
                'id' => 11,
                'idinforme' => '11',
                'url_informe' => 'https://uca.edu.sv/iudop/wp-content/uploads/Informe11.pdf',
                'titulo' => 'Los salvadoreños ante el proceso de paz en El Salvador y Centroamérica',
                'fecha_inicio' => '1987-02-12',
                'fecha_fin' => '1987-02-12',
                'tipo_informe' => 1,
                'eliminado' => 0,
                'idusuario' => NULL,
                'created_at' => '2021-07-07 05:02:57',
                'updated_at' => '2021-07-07 05:02:57',
            ),
            11 => 
            array (
                'id' => 12,
                'idinforme' => '12',
                'url_informe' => 'https://uca.edu.sv/iudop/wp-content/uploads/informe121-1.pdf',
                'titulo' => 'Los salvadoreños ante las próximas elecciones ',
                'fecha_inicio' => '1987-11-28',
                'fecha_fin' => '1987-12-06',
                'tipo_informe' => 4,
                'eliminado' => 0,
                'idusuario' => NULL,
                'created_at' => '2021-07-07 05:02:57',
                'updated_at' => '2021-07-07 05:02:57',
            ),
            12 => 
            array (
                'id' => 13,
                'idinforme' => '13',
                'url_informe' => 'https://uca.edu.sv/iudop/wp-content/uploads/informe131-1.pdf',
                'titulo' => 'Encuesta preelectoral sobre el 20 de marzo',
                'fecha_inicio' => '1988-03-05',
                'fecha_fin' => '1988-03-09',
                'tipo_informe' => 4,
                'eliminado' => 0,
                'idusuario' => NULL,
                'created_at' => '2021-07-07 05:02:57',
                'updated_at' => '2021-07-07 05:02:57',
            ),
            13 => 
            array (
                'id' => 14,
                'idinforme' => '15',
                'url_informe' => 'https://uca.edu.sv/iudop/wp-content/uploads/informe15.pdf',
                'titulo' => 'Sentir político de los salvadoreños tras las elecciones del 20 de marzo de 1988',
                'fecha_inicio' => '1988-05-07',
                'fecha_fin' => '1988-05-22',
                'tipo_informe' => 5,
                'eliminado' => 0,
                'idusuario' => NULL,
                'created_at' => '2021-07-07 05:02:57',
                'updated_at' => '2021-07-07 05:02:57',
            ),
            14 => 
            array (
                'id' => 15,
                'idinforme' => '16',
                'url_informe' => 'https://uca.edu.sv/iudop/wp-content/uploads/informe16.pdf',
                'titulo' => 'La opinión de los salvadoreños sobre la paz en El Salvador',
                'fecha_inicio' => '1988-07-21',
                'fecha_fin' => '1988-08-11',
                'tipo_informe' => 1,
                'eliminado' => 0,
                'idusuario' => NULL,
                'created_at' => '2021-07-07 05:02:57',
                'updated_at' => '2021-07-07 05:02:57',
            ),
            15 => 
            array (
                'id' => 16,
                'idinforme' => '17',
                'url_informe' => 'https://uca.edu.sv/iudop/wp-content/uploads/informe17.pdf',
                'titulo' => 'La religión para los salvadoreños',
                'fecha_inicio' => '1988-06-11',
                'fecha_fin' => '1988-06-26',
                'tipo_informe' => 2,
                'eliminado' => 0,
                'idusuario' => NULL,
                'created_at' => '2021-07-07 05:02:57',
                'updated_at' => '2021-07-07 05:02:57',
            ),
            16 => 
            array (
                'id' => 17,
                'idinforme' => '19',
                'url_informe' => 'https://uca.edu.sv/iudop/wp-content/uploads/informe192.pdf',
                'titulo' => 'La opinión de los salvadoreños sobre el año 1988',
                'fecha_inicio' => '1988-11-26',
                'fecha_fin' => '1988-12-19',
                'tipo_informe' => 6,
                'eliminado' => 0,
                'idusuario' => NULL,
                'created_at' => '2021-07-07 05:02:57',
                'updated_at' => '2021-07-07 05:02:57',
            ),
            17 => 
            array (
                'id' => 18,
                'idinforme' => '20',
                'url_informe' => 'https://uca.edu.sv/iudop/wp-content/uploads/informe20.pdf',
                'titulo' => 'Cristiani con notable ventaje sobre Chavez Mena para elección presindencial del 19 de marzo ',
                'fecha_inicio' => '1989-03-02',
                'fecha_fin' => '1989-03-14',
                'tipo_informe' => 7,
                'eliminado' => 0,
                'idusuario' => NULL,
                'created_at' => '2021-07-07 05:02:57',
                'updated_at' => '2021-07-07 05:02:57',
            ),
            18 => 
            array (
                'id' => 19,
                'idinforme' => '21',
                'url_informe' => 'https://uca.edu.sv/iudop/wp-content/uploads/informe21.pdf',
                'titulo' => 'Expectativas de los salvadoreños sobre el Gobierno de ARENA',
                'fecha_inicio' => '1989-05-06',
                'fecha_fin' => '1989-05-20',
                'tipo_informe' => 8,
                'eliminado' => 0,
                'idusuario' => NULL,
                'created_at' => '2021-07-07 05:02:57',
                'updated_at' => '2021-07-07 05:02:57',
            ),
            19 => 
            array (
                'id' => 20,
                'idinforme' => '22',
                'url_informe' => 'https://uca.edu.sv/iudop/wp-content/uploads/informe22.pdf',
                'titulo' => 'Situación y sentir de empleados y desempleados urbanos de El Salvador',
                'fecha_inicio' => '1989-07-22',
                'fecha_fin' => '1989-08-20',
                'tipo_informe' => 2,
                'eliminado' => 0,
                'idusuario' => NULL,
                'created_at' => '2021-07-07 05:02:57',
                'updated_at' => '2021-07-07 05:02:57',
            ),
            20 => 
            array (
                'id' => 21,
                'idinforme' => '23',
                'url_informe' => 'https://uca.edu.sv/iudop/wp-content/uploads/informe23.pdf',
                'titulo' => 'Los primeros 100 días de Cristiani para la opinión pública salvadoreña ',
                'fecha_inicio' => '1989-09-02',
                'fecha_fin' => '1989-09-22',
                'tipo_informe' => 9,
                'eliminado' => 0,
                'idusuario' => NULL,
                'created_at' => '2021-07-07 05:02:57',
                'updated_at' => '2021-07-07 05:02:57',
            ),
            21 => 
            array (
                'id' => 22,
                'idinforme' => '25',
                'url_informe' => 'https://uca.edu.sv/iudop/wp-content/uploads/informe25_organized.pdf',
                'titulo' => 'Los salvadoreños ante el primer año de Gobierno de Alfredo Cristiani',
                'fecha_inicio' => '1990-06-09',
                'fecha_fin' => '1990-07-07',
                'tipo_informe' => 10,
                'eliminado' => 0,
                'idusuario' => NULL,
                'created_at' => '2021-07-07 05:02:57',
                'updated_at' => '2021-07-07 05:02:57',
            ),
            22 => 
            array (
                'id' => 23,
                'idinforme' => '26',
                'url_informe' => 'https://uca.edu.sv/iudop/wp-content/uploads/informe26.pdf',
                'titulo' => 'Los salvadoreños ante el año 1990',
                'fecha_inicio' => '1991-01-12',
                'fecha_fin' => '1991-01-26',
                'tipo_informe' => 11,
                'eliminado' => 0,
                'idusuario' => NULL,
                'created_at' => '2021-07-07 05:02:57',
                'updated_at' => '2021-07-07 05:02:57',
            ),
            23 => 
            array (
                'id' => 24,
                'idinforme' => '27',
                'url_informe' => 'https://uca.edu.sv/iudop/wp-content/uploads/informe27.pdf',
                'titulo' => 'Los salvadoreños ante las elecciones de diputados y alcaldes municipales del 10 de marzo de 1991',
                'fecha_inicio' => '1991-02-01',
                'fecha_fin' => '1991-02-28',
                'tipo_informe' => 4,
                'eliminado' => 0,
                'idusuario' => NULL,
                'created_at' => '2021-07-07 05:02:57',
                'updated_at' => '2021-07-07 05:02:57',
            ),
            24 => 
            array (
                'id' => 25,
                'idinforme' => '30',
                'url_informe' => 'https://uca.edu.sv/iudop/wp-content/uploads/informe30.pdf',
                'titulo' => 'Los salvadoreños ante los procesos de privatización y de paz en el país',
                'fecha_inicio' => '1991-10-12',
                'fecha_fin' => '1991-11-02',
                'tipo_informe' => 2,
                'eliminado' => 0,
                'idusuario' => NULL,
                'created_at' => '2021-07-07 05:02:57',
                'updated_at' => '2021-07-07 05:02:57',
            ),
            25 => 
            array (
                'id' => 26,
                'idinforme' => '31',
                'url_informe' => 'https://uca.edu.sv/iudop/wp-content/uploads/informe31.pdf',
                'titulo' => 'Los salvadoreños ante los Acuerdos finales de paz',
                'fecha_inicio' => '1992-01-18',
                'fecha_fin' => '1992-02-01',
                'tipo_informe' => 1,
                'eliminado' => 0,
                'idusuario' => NULL,
                'created_at' => '2021-07-07 05:02:57',
                'updated_at' => '2021-07-07 05:02:57',
            ),
            26 => 
            array (
                'id' => 27,
                'idinforme' => '32',
                'url_informe' => 'https://uca.edu.sv/iudop/wp-content/uploads/informe32.pdf',
                'titulo' => 'Visión del cumplimiento de los Acuerdos de paz y valoraciones políticas de los salvadoreños',
                'fecha_inicio' => '1992-05-30',
                'fecha_fin' => '1992-06-13',
                'tipo_informe' => 1,
                'eliminado' => 0,
                'idusuario' => NULL,
                'created_at' => '2021-07-07 05:02:57',
                'updated_at' => '2021-07-07 05:02:57',
            ),
            27 => 
            array (
                'id' => 28,
                'idinforme' => '33',
                'url_informe' => 'https://uca.edu.sv/iudop/wp-content/uploads/informe33-2-25.pdf',
                'titulo' => 'Seguimiento de los Acuerdos de paz y opiniones sobre coyuntura económica y potítica del país',
                'fecha_inicio' => '1992-10-10',
                'fecha_fin' => '1992-10-18',
                'tipo_informe' => 1,
                'eliminado' => 0,
                'idusuario' => NULL,
                'created_at' => '2021-07-07 05:02:57',
                'updated_at' => '2021-07-07 05:02:57',
            ),
            28 => 
            array (
                'id' => 29,
                'idinforme' => '34',
                'url_informe' => 'https://uca.edu.sv/iudop/wp-content/uploads/informe34.pdf',
                'titulo' => 'Encuesta exploratoria sobre delincuencia urbana',
                'fecha_inicio' => '1993-02-13',
                'fecha_fin' => '1993-02-20',
                'tipo_informe' => 2,
                'eliminado' => 0,
                'idusuario' => NULL,
                'created_at' => '2021-07-07 05:02:57',
                'updated_at' => '2021-07-07 05:02:57',
            ),
            29 => 
            array (
                'id' => 30,
                'idinforme' => '35',
                'url_informe' => 'https://uca.edu.sv/iudop/wp-content/uploads/informe35.pdf',
                'titulo' => 'La opinión de los salvadoreños sobre el proceso electoral consulta de junio de 1993',
                'fecha_inicio' => '1993-06-10',
                'fecha_fin' => '1993-06-26',
                'tipo_informe' => 4,
                'eliminado' => 0,
                'idusuario' => NULL,
                'created_at' => '2021-07-07 05:02:57',
                'updated_at' => '2021-07-07 05:02:57',
            ),
            30 => 
            array (
                'id' => 31,
                'idinforme' => '36',
                'url_informe' => 'https://uca.edu.sv/iudop/wp-content/uploads/informe36.pdf',
                'titulo' => 'Lo que debe hacer el próximo Gobierno sobre los problemas del país según la opinión pública salvadoreña ',
                'fecha_inicio' => '1993-08-21',
                'fecha_fin' => '1993-08-28',
                'tipo_informe' => 8,
                'eliminado' => 0,
                'idusuario' => NULL,
                'created_at' => '2021-07-07 05:02:57',
                'updated_at' => '2021-07-07 05:02:57',
            ),
            31 => 
            array (
                'id' => 32,
                'idinforme' => '37',
                'url_informe' => 'https://uca.edu.sv/iudop/wp-content/uploads/informe37.pdf',
                'titulo' => 'Los salvadoreños y las elecciones de 1994 ',
                'fecha_inicio' => '1993-10-16',
                'fecha_fin' => '1993-10-23',
                'tipo_informe' => 4,
                'eliminado' => 0,
                'idusuario' => NULL,
                'created_at' => '2021-07-07 05:02:57',
                'updated_at' => '2021-07-07 05:02:57',
            ),
            32 => 
            array (
                'id' => 33,
                'idinforme' => '38',
                'url_informe' => 'https://uca.edu.sv/iudop/wp-content/uploads/informe38.pdf',
                'titulo' => 'Los salvadoreños y la evaluación del año 1993',
                'fecha_inicio' => '1993-12-04',
                'fecha_fin' => '1993-12-12',
                'tipo_informe' => 12,
                'eliminado' => 0,
                'idusuario' => NULL,
                'created_at' => '2021-07-07 05:02:57',
                'updated_at' => '2021-07-07 05:02:57',
            ),
            33 => 
            array (
                'id' => 34,
                'idinforme' => '39',
                'url_informe' => 'https://uca.edu.sv/iudop/wp-content/uploads/informe39.pdf',
                'titulo' => 'La opinión de los salvadoreños sobre las elecciones de febrero de 1994',
                'fecha_inicio' => '1994-02-05',
                'fecha_fin' => '1994-02-13',
                'tipo_informe' => 4,
                'eliminado' => 0,
                'idusuario' => NULL,
                'created_at' => '2021-07-07 05:02:57',
                'updated_at' => '2021-07-07 05:02:57',
            ),
            34 => 
            array (
                'id' => 35,
                'idinforme' => '43',
                'url_informe' => 'https://uca.edu.sv/iudop/wp-content/uploads/informe431.pdf',
                'titulo' => 'Encuesta de evaluación poselectoral y expectativas hacia el nuevo Gobierno',
                'fecha_inicio' => '1994-05-21',
                'fecha_fin' => '1994-05-29',
                'tipo_informe' => 8,
                'eliminado' => 0,
                'idusuario' => NULL,
                'created_at' => '2021-07-07 05:02:57',
                'updated_at' => '2021-07-07 05:02:57',
            ),
            35 => 
            array (
                'id' => 36,
                'idinforme' => '46',
                'url_informe' => 'https://uca.edu.sv/iudop/wp-content/uploads/informe46.pdf',
                'titulo' => 'La opinión de los salvadoreños sobre el plan económico del Gobierno',
                'fecha_inicio' => '1995-01-28',
                'fecha_fin' => '1995-02-05',
                'tipo_informe' => 2,
                'eliminado' => 0,
                'idusuario' => NULL,
                'created_at' => '2021-07-07 05:02:57',
                'updated_at' => '2021-07-07 05:02:57',
            ),
            36 => 
            array (
                'id' => 37,
                'idinforme' => '47',
                'url_informe' => 'https://uca.edu.sv/iudop/wp-content/uploads/informe47.pdf',
                'titulo' => 'La opinión de los salvadoreños sobre la situación de los derechos humanos y los retos de la procuradora',
                'fecha_inicio' => '1995-03-11',
                'fecha_fin' => '1995-03-19',
                'tipo_informe' => 2,
                'eliminado' => 0,
                'idusuario' => NULL,
                'created_at' => '2021-07-07 05:02:57',
                'updated_at' => '2021-07-07 05:02:57',
            ),
            37 => 
            array (
                'id' => 38,
                'idinforme' => '48',
                'url_informe' => 'https://uca.edu.sv/iudop/wp-content/uploads/informe48.pdf',
                'titulo' => 'La opinión de los salvadoreños sobre el primer año de Gobierno de Calderón Sol',
                'fecha_inicio' => '1995-05-20',
                'fecha_fin' => '1995-05-21',
                'tipo_informe' => 13,
                'eliminado' => 0,
                'idusuario' => NULL,
                'created_at' => '2021-07-07 05:02:57',
                'updated_at' => '2021-07-07 05:02:57',
            ),
            38 => 
            array (
                'id' => 39,
                'idinforme' => '49',
                'url_informe' => 'https://uca.edu.sv/iudop/wp-content/uploads/informe49.pdf',
                'titulo' => 'La religión de los salvadoreños y la opinión sobre los retos del nuevo Arzobispo',
                'fecha_inicio' => '1995-05-27',
                'fecha_fin' => '1995-06-03',
                'tipo_informe' => 2,
                'eliminado' => 0,
                'idusuario' => NULL,
                'created_at' => '2021-07-07 05:02:57',
                'updated_at' => '2021-07-07 05:02:57',
            ),
            39 => 
            array (
                'id' => 40,
                'idinforme' => '50',
                'url_informe' => 'https://uca.edu.sv/iudop/wp-content/uploads/informe50.pdf',
                'titulo' => 'Sondeo sobre la Procuraduría para la Defensa de los Derechos Humanos',
                'fecha_inicio' => '1995-09-30',
                'fecha_fin' => '1995-10-07',
                'tipo_informe' => 2,
                'eliminado' => 0,
                'idusuario' => NULL,
                'created_at' => '2021-07-07 05:02:57',
                'updated_at' => '2021-07-07 05:02:57',
            ),
            40 => 
            array (
                'id' => 41,
                'idinforme' => '51',
                'url_informe' => 'https://uca.edu.sv/iudop/wp-content/uploads/informe51.pdf',
                'titulo' => 'La opinión de los salvadoreños sobre la situación política del país',
                'fecha_inicio' => '1995-10-21',
                'fecha_fin' => '1995-10-28',
                'tipo_informe' => 2,
                'eliminado' => 0,
                'idusuario' => NULL,
                'created_at' => '2021-07-07 05:02:57',
                'updated_at' => '2021-07-07 05:02:57',
            ),
            41 => 
            array (
                'id' => 42,
                'idinforme' => '52',
                'url_informe' => 'https://uca.edu.sv/iudop/wp-content/uploads/informe52.pdf',
                'titulo' => 'Los salvadoreños evalúan el año 1995',
                'fecha_inicio' => '1995-12-02',
                'fecha_fin' => '1995-12-09',
                'tipo_informe' => 14,
                'eliminado' => 0,
                'idusuario' => NULL,
                'created_at' => '2021-07-07 05:02:57',
                'updated_at' => '2021-07-07 05:02:57',
            ),
            42 => 
            array (
                'id' => 43,
                'idinforme' => '53',
                'url_informe' => NULL,
                'titulo' => 'Sondeo nacional sobre la percepción infantil hacia los agentes de Seguridad Pública',
                'fecha_inicio' => '1000-01-01',
                'fecha_fin' => '1000-01-01',
                'tipo_informe' => 2,
                'eliminado' => 0,
                'idusuario' => NULL,
                'created_at' => '2021-07-07 05:02:57',
                'updated_at' => '2021-07-07 05:02:57',
            ),
            43 => 
            array (
                'id' => 44,
                'idinforme' => '54',
                'url_informe' => 'https://uca.edu.sv/iudop/wp-content/uploads/informe54.pdf',
                'titulo' => 'Los salvadoreños opinan sobre la delincuencia común y la Ley de emergencia',
                'fecha_inicio' => '1996-05-05',
                'fecha_fin' => '1996-05-12',
                'tipo_informe' => 2,
                'eliminado' => 0,
                'idusuario' => NULL,
                'created_at' => '2021-07-07 05:02:57',
                'updated_at' => '2021-07-07 05:02:57',
            ),
            44 => 
            array (
                'id' => 45,
                'idinforme' => '55',
                'url_informe' => 'https://uca.edu.sv/iudop/wp-content/uploads/informe55.pdf',
                'titulo' => 'Los salvadoreños evalúan los dos años de Gobierno de Calderón Sol',
                'fecha_inicio' => '1996-05-25',
                'fecha_fin' => '1996-05-30',
                'tipo_informe' => 15,
                'eliminado' => 0,
                'idusuario' => NULL,
                'created_at' => '2021-07-07 05:02:57',
                'updated_at' => '2021-07-07 05:02:57',
            ),
            45 => 
            array (
                'id' => 46,
                'idinforme' => '56',
                'url_informe' => 'https://uca.edu.sv/iudop/wp-content/uploads/informe56.pdf',
                'titulo' => 'Encuesta infantil: opiniones sobre la escuela y la salud',
                'fecha_inicio' => '1000-01-01',
                'fecha_fin' => '1000-01-01',
                'tipo_informe' => 2,
                'eliminado' => 0,
                'idusuario' => NULL,
                'created_at' => '2021-07-07 05:02:57',
                'updated_at' => '2021-07-07 05:02:57',
            ),
            46 => 
            array (
                'id' => 47,
                'idinforme' => '57',
                'url_informe' => 'https://uca.edu.sv/iudop/wp-content/uploads/informe57.pdf',
                'titulo' => 'Los salvadoreños opinan sobre el sistema de justicia y los derechos humanos ',
                'fecha_inicio' => '1996-07-13',
                'fecha_fin' => '1996-08-09',
                'tipo_informe' => 2,
                'eliminado' => 0,
                'idusuario' => NULL,
                'created_at' => '2021-07-07 05:02:57',
                'updated_at' => '2021-07-07 05:02:57',
            ),
            47 => 
            array (
                'id' => 48,
                'idinforme' => '58',
                'url_informe' => 'https://uca.edu.sv/iudop/wp-content/uploads/informe58.pdf',
                'titulo' => 'Encuesta sobre derechos laborales y el movimiento sindical en la industria de la maquila',
                'fecha_inicio' => '1996-11-12',
                'fecha_fin' => '1996-11-16',
                'tipo_informe' => 16,
                'eliminado' => 0,
                'idusuario' => NULL,
                'created_at' => '2021-07-07 05:02:57',
                'updated_at' => '2021-07-07 05:02:57',
            ),
            48 => 
            array (
                'id' => 49,
                'idinforme' => '59',
                'url_informe' => 'https://uca.edu.sv/iudop/wp-content/uploads/informe59.pdf',
                'titulo' => 'Sondeo sobre violencia en los centros educativos del área de San Salvador',
                'fecha_inicio' => '1996-09-30',
                'fecha_fin' => '1996-10-18',
                'tipo_informe' => 2,
                'eliminado' => 0,
                'idusuario' => NULL,
                'created_at' => '2021-07-07 05:02:57',
                'updated_at' => '2021-07-07 05:02:57',
            ),
            49 => 
            array (
                'id' => 50,
                'idinforme' => '60',
                'url_informe' => 'https://uca.edu.sv/iudop/wp-content/uploads/informe60.pdf',
                'titulo' => 'Los salvadoreños evalúan el año 1996',
                'fecha_inicio' => '1996-11-23',
                'fecha_fin' => '1996-12-01',
                'tipo_informe' => 17,
                'eliminado' => 0,
                'idusuario' => NULL,
                'created_at' => '2021-07-07 05:02:57',
                'updated_at' => '2021-07-07 05:02:57',
            ),
            50 => 
            array (
                'id' => 51,
                'idinforme' => '61',
                'url_informe' => 'https://uca.edu.sv/iudop/wp-content/uploads/informe61.pdf',
                'titulo' => 'La opinión de los salvadoreños sobre el proceso electoral de 1997',
                'fecha_inicio' => '1997-02-01',
                'fecha_fin' => '1997-02-09',
                'tipo_informe' => 4,
                'eliminado' => 0,
                'idusuario' => NULL,
                'created_at' => '2021-07-07 05:02:57',
                'updated_at' => '2021-07-07 05:02:57',
            ),
            51 => 
            array (
                'id' => 52,
                'idinforme' => '62',
                'url_informe' => 'https://uca.edu.sv/iudop/wp-content/uploads/informe62.pdf',
                'titulo' => 'La jornada electoral del 16 de marzo en San Salvador',
                'fecha_inicio' => '1997-03-23',
                'fecha_fin' => '1997-03-24',
                'tipo_informe' => 18,
                'eliminado' => 0,
                'idusuario' => NULL,
                'created_at' => '2021-07-07 05:02:57',
                'updated_at' => '2021-07-07 05:02:57',
            ),
            52 => 
            array (
                'id' => 53,
                'idinforme' => '63',
                'url_informe' => 'https://uca.edu.sv/iudop/wp-content/uploads/informe631.pdf',
                'titulo' => 'Los salvadoreños evaluán los tres años de Gobierno de Armando Calderón Sol',
                'fecha_inicio' => '1997-05-17',
                'fecha_fin' => '1997-05-25',
                'tipo_informe' => 19,
                'eliminado' => 0,
                'idusuario' => NULL,
                'created_at' => '2021-07-07 05:02:57',
                'updated_at' => '2021-07-07 05:02:57',
            ),
            53 => 
            array (
                'id' => 54,
                'idinforme' => '64',
                'url_informe' => 'https://uca.edu.sv/iudop/wp-content/uploads/INFORME64-1.pdf',
                'titulo' => 'Los salvadoreños y las expectativas hacia las autoridades del país',
                'fecha_inicio' => '1997-07-13',
                'fecha_fin' => '1997-07-21',
                'tipo_informe' => 2,
                'eliminado' => 0,
                'idusuario' => NULL,
                'created_at' => '2021-07-07 05:02:57',
                'updated_at' => '2021-07-07 05:02:57',
            ),
            54 => 
            array (
                'id' => 55,
                'idinforme' => '65',
                'url_informe' => 'https://uca.edu.sv/iudop/wp-content/uploads/informe65.pdf',
                'titulo' => 'Encuesta sobre el sistema educativo y la salud',
                'fecha_inicio' => '1997-11-01',
                'fecha_fin' => '1997-11-10',
                'tipo_informe' => 2,
                'eliminado' => 0,
                'idusuario' => NULL,
                'created_at' => '2021-07-07 05:02:57',
                'updated_at' => '2021-07-07 05:02:57',
            ),
            55 => 
            array (
                'id' => 56,
                'idinforme' => '66',
                'url_informe' => 'https://uca.edu.sv/iudop/wp-content/uploads/informe66.pdf',
                'titulo' => 'Los salvadoreños evalúan el año 1997',
                'fecha_inicio' => '1997-09-29',
                'fecha_fin' => '1997-12-07',
                'tipo_informe' => 20,
                'eliminado' => 0,
                'idusuario' => NULL,
                'created_at' => '2021-07-07 05:02:57',
                'updated_at' => '2021-07-07 05:02:57',
            ),
            56 => 
            array (
                'id' => 57,
                'idinforme' => '67',
                'url_informe' => 'https://uca.edu.sv/iudop/wp-content/uploads/informe67.pdf',
                'titulo' => 'La opinión pública sobre los derechos humanos y los retos de la PDDH',
                'fecha_inicio' => '1998-02-07',
                'fecha_fin' => '1998-02-14',
                'tipo_informe' => 2,
                'eliminado' => 0,
                'idusuario' => NULL,
                'created_at' => '2021-07-07 05:02:57',
                'updated_at' => '2021-07-07 05:02:57',
            ),
            57 => 
            array (
                'id' => 58,
                'idinforme' => '68',
                'url_informe' => 'https://uca.edu.sv/iudop/wp-content/uploads/informe68.pdf',
                'titulo' => 'Encuesta sobre religión y religiosidad de los salvadoreños',
                'fecha_inicio' => '1998-05-03',
                'fecha_fin' => '1998-05-11',
                'tipo_informe' => 2,
                'eliminado' => 0,
                'idusuario' => NULL,
                'created_at' => '2021-07-07 05:02:57',
                'updated_at' => '2021-07-07 05:02:57',
            ),
            58 => 
            array (
                'id' => 59,
                'idinforme' => '69',
                'url_informe' => 'https://uca.edu.sv/iudop/wp-content/uploads/informe69.pdf',
                'titulo' => 'Los Salvadoreños evalúan el desempeño del Ejecutivo, de la Asamblea y de la alcadía capitalina',
                'fecha_inicio' => '1998-05-23',
                'fecha_fin' => '1998-05-26',
                'tipo_informe' => 21,
                'eliminado' => 0,
                'idusuario' => NULL,
                'created_at' => '2021-07-07 05:02:57',
                'updated_at' => '2021-07-07 05:02:57',
            ),
            59 => 
            array (
                'id' => 60,
                'idinforme' => '70',
                'url_informe' => 'https://uca.edu.sv/iudop/wp-content/uploads/informe70.pdf',
                'titulo' => 'Los salvadoreños opinan sobre el problema de la delincuencia',
                'fecha_inicio' => '1998-08-04',
                'fecha_fin' => '1998-08-12',
                'tipo_informe' => 2,
                'eliminado' => 0,
                'idusuario' => NULL,
                'created_at' => '2021-07-07 05:02:57',
                'updated_at' => '2021-07-07 05:02:57',
            ),
            60 => 
            array (
                'id' => 61,
                'idinforme' => '71',
                'url_informe' => 'https://uca.edu.sv/iudop/wp-content/uploads/informe71.pdf',
                'titulo' => 'Encuesta sobre cultura política',
                'fecha_inicio' => '1998-10-17',
                'fecha_fin' => '1998-10-18',
                'tipo_informe' => 2,
                'eliminado' => 0,
                'idusuario' => NULL,
                'created_at' => '2021-07-07 05:02:57',
                'updated_at' => '2021-07-07 05:02:57',
            ),
            61 => 
            array (
                'id' => 62,
                'idinforme' => '72',
                'url_informe' => 'https://uca.edu.sv/iudop/wp-content/uploads/informe72.pdf',
                'titulo' => 'Evaluación del país a finales de 1998',
                'fecha_inicio' => '1998-12-10',
                'fecha_fin' => '1998-12-15',
                'tipo_informe' => 22,
                'eliminado' => 0,
                'idusuario' => NULL,
                'created_at' => '2021-07-07 05:02:57',
                'updated_at' => '2021-07-07 05:02:57',
            ),
            62 => 
            array (
                'id' => 63,
                'idinforme' => '73',
                'url_informe' => 'https://uca.edu.sv/iudop/wp-content/uploads/informe73.pdf',
                'titulo' => 'Los salvadoreños frente a las elecciones presidenciales del año 1999',
                'fecha_inicio' => '1999-02-06',
                'fecha_fin' => '1999-02-11',
                'tipo_informe' => 4,
                'eliminado' => 0,
                'idusuario' => NULL,
                'created_at' => '2021-07-07 05:02:57',
                'updated_at' => '2021-07-07 05:02:57',
            ),
            63 => 
            array (
                'id' => 64,
                'idinforme' => '74',
                'url_informe' => 'https://uca.edu.sv/iudop/wp-content/uploads/informe74.pdf',
                'titulo' => 'La opinión de los votantes sobre la jornada electoral',
                'fecha_inicio' => '1999-03-07',
                'fecha_fin' => '1999-03-08',
                'tipo_informe' => 18,
                'eliminado' => 0,
                'idusuario' => NULL,
                'created_at' => '2021-07-07 05:02:57',
                'updated_at' => '2021-07-07 05:02:57',
            ),
            64 => 
            array (
                'id' => 65,
                'idinforme' => '75',
                'url_informe' => 'https://uca.edu.sv/iudop/wp-content/uploads/informe75.pdf',
                'titulo' => 'Encuesta de evaluación poselectoral',
                'fecha_inicio' => '1999-04-23',
                'fecha_fin' => '1999-05-03',
                'tipo_informe' => 5,
                'eliminado' => 0,
                'idusuario' => NULL,
                'created_at' => '2021-07-07 05:02:57',
                'updated_at' => '2021-07-07 05:02:57',
            ),
            65 => 
            array (
                'id' => 66,
                'idinforme' => '76',
                'url_informe' => 'https://uca.edu.sv/iudop/wp-content/uploads/informe76.pdf',
                'titulo' => 'Los salvadoreños evalúan el Gobierno de Calderon Sol y formulan expectativas hacia el nuevo Gobierno',
                'fecha_inicio' => '1999-05-12',
                'fecha_fin' => '1999-05-18',
                'tipo_informe' => 23,
                'eliminado' => 0,
                'idusuario' => NULL,
                'created_at' => '2021-07-07 05:02:57',
                'updated_at' => '2021-07-07 05:02:57',
            ),
            66 => 
            array (
                'id' => 67,
                'idinforme' => '78',
                'url_informe' => 'https://uca.edu.sv/iudop/wp-content/uploads/informe78.pdf',
                'titulo' => 'Encuesta de victimización en los municipios de Sonsonate y Cojutepeque',
                'fecha_inicio' => '1999-06-05',
                'fecha_fin' => '1999-07-13',
                'tipo_informe' => 2,
                'eliminado' => 0,
                'idusuario' => NULL,
                'created_at' => '2021-07-07 05:02:57',
                'updated_at' => '2021-07-07 05:02:57',
            ),
            67 => 
            array (
                'id' => 68,
                'idinforme' => '79',
                'url_informe' => 'https://uca.edu.sv/iudop/wp-content/uploads/informe79.pdf',
                'titulo' => 'Los salvadoreños evalúan los cien días de Gobierno de Francisco Flores',
                'fecha_inicio' => '1999-06-18',
                'fecha_fin' => '1999-06-22',
                'tipo_informe' => 24,
                'eliminado' => 0,
                'idusuario' => NULL,
                'created_at' => '2021-07-07 05:02:57',
                'updated_at' => '2021-07-07 05:02:57',
            ),
            68 => 
            array (
                'id' => 69,
                'idinforme' => '80',
                'url_informe' => 'https://uca.edu.sv/iudop/wp-content/uploads/informe80.pdf',
                'titulo' => 'Encuesta sobre valores',
                'fecha_inicio' => '1999-08-25',
                'fecha_fin' => '1999-08-30',
                'tipo_informe' => 2,
                'eliminado' => 0,
                'idusuario' => NULL,
                'created_at' => '2021-07-07 05:02:57',
                'updated_at' => '2021-07-07 05:02:57',
            ),
            69 => 
            array (
                'id' => 70,
                'idinforme' => '81',
                'url_informe' => 'https://uca.edu.sv/iudop/wp-content/uploads/informe82.pdf',
                'titulo' => 'La situación de la mujer en El Salvador',
                'fecha_inicio' => '1999-10-10',
                'fecha_fin' => '1999-10-24',
                'tipo_informe' => 2,
                'eliminado' => 0,
                'idusuario' => NULL,
                'created_at' => '2021-07-07 05:02:57',
                'updated_at' => '2021-07-07 05:02:57',
            ),
            70 => 
            array (
                'id' => 71,
                'idinforme' => '82',
                'url_informe' => 'https://uca.edu.sv/iudop/wp-content/uploads/informe81.pdf',
                'titulo' => 'Evaluación del país a finales de 1999 y perspectivas eclectorales para el 2000',
                'fecha_inicio' => '1999-09-18',
                'fecha_fin' => '1999-09-26',
                'tipo_informe' => 25,
                'eliminado' => 0,
                'idusuario' => NULL,
                'created_at' => '2021-07-07 05:02:57',
                'updated_at' => '2021-07-07 05:02:57',
            ),
            71 => 
            array (
                'id' => 72,
                'idinforme' => '83',
                'url_informe' => 'https://uca.edu.sv/iudop/wp-content/uploads/informe83.pdf',
                'titulo' => 'Los salvadoreños frente a las elecciones legislativas y municipales de 2000',
                'fecha_inicio' => '1999-12-04',
                'fecha_fin' => '1999-12-08',
                'tipo_informe' => 4,
                'eliminado' => 0,
                'idusuario' => NULL,
                'created_at' => '2021-07-07 05:02:57',
                'updated_at' => '2021-07-07 05:02:57',
            ),
            72 => 
            array (
                'id' => 73,
                'idinforme' => '84',
                'url_informe' => 'https://uca.edu.sv/iudop/wp-content/uploads/informe84.pdf',
                'titulo' => 'Opiniones de los capitalinos sobre el proceso electoral 2000',
                'fecha_inicio' => '2000-02-12',
                'fecha_fin' => '2000-02-20',
                'tipo_informe' => 18,
                'eliminado' => 0,
                'idusuario' => NULL,
                'created_at' => '2021-07-07 05:02:57',
                'updated_at' => '2021-07-07 05:02:57',
            ),
            73 => 
            array (
                'id' => 74,
                'idinforme' => '85',
                'url_informe' => 'https://uca.edu.sv/iudop/wp-content/uploads/informe85.pdf',
                'titulo' => 'Los salvadoreños evalúan el primer año del Gobierno de Francisco Flores',
                'fecha_inicio' => '2000-03-12',
                'fecha_fin' => '2000-03-13',
                'tipo_informe' => 26,
                'eliminado' => 0,
                'idusuario' => NULL,
                'created_at' => '2021-07-07 05:02:57',
                'updated_at' => '2021-07-07 05:02:57',
            ),
            74 => 
            array (
                'id' => 75,
                'idinforme' => '86',
                'url_informe' => 'https://uca.edu.sv/iudop/wp-content/uploads/informe86.pdf',
                'titulo' => 'Encuesta de evaluación del año 2000',
                'fecha_inicio' => '2000-05-20',
                'fecha_fin' => '2000-05-25',
                'tipo_informe' => 27,
                'eliminado' => 0,
                'idusuario' => NULL,
                'created_at' => '2021-07-07 05:02:57',
                'updated_at' => '2021-07-07 05:02:57',
            ),
            75 => 
            array (
                'id' => 76,
                'idinforme' => '87',
                'url_informe' => 'https://uca.edu.sv/iudop/wp-content/uploads/informe87.pdf',
                'titulo' => 'Los salvadoreños opinan sobre los terremotos',
                'fecha_inicio' => '2000-11-30',
                'fecha_fin' => '2000-12-05',
                'tipo_informe' => 2,
                'eliminado' => 0,
                'idusuario' => NULL,
                'created_at' => '2021-07-07 05:02:57',
                'updated_at' => '2021-07-07 05:02:57',
            ),
            76 => 
            array (
                'id' => 77,
                'idinforme' => '88',
                'url_informe' => 'https://uca.edu.sv/iudop/wp-content/uploads/informe88.pdf',
                'titulo' => 'Los salvadoreños evalúan el segundo año del Gobierno de Francisco Flores',
                'fecha_inicio' => '2001-04-05',
                'fecha_fin' => '2001-04-11',
                'tipo_informe' => 28,
                'eliminado' => 0,
                'idusuario' => NULL,
                'created_at' => '2021-07-07 05:02:57',
                'updated_at' => '2021-07-07 05:02:57',
            ),
            77 => 
            array (
                'id' => 78,
                'idinforme' => '89',
                'url_informe' => 'https://uca.edu.sv/iudop/wp-content/uploads/informe89.pdf',
                'titulo' => 'Los salvadoreños opinan sobre el sistema educativo',
                'fecha_inicio' => '2001-05-20',
                'fecha_fin' => '2001-05-27',
                'tipo_informe' => 2,
                'eliminado' => 0,
                'idusuario' => NULL,
                'created_at' => '2021-07-07 05:02:57',
                'updated_at' => '2021-07-07 05:02:57',
            ),
            78 => 
            array (
                'id' => 79,
                'idinforme' => '90',
                'url_informe' => 'https://uca.edu.sv/iudop/wp-content/uploads/informe90.pdf',
                'titulo' => 'Encuesta nacional de actitudes, normas y valores en torno a la violencia y uso de armas de fuego',
                'fecha_inicio' => '2001-03-15',
                'fecha_fin' => '2001-03-19',
                'tipo_informe' => 2,
                'eliminado' => 0,
                'idusuario' => NULL,
                'created_at' => '2021-07-07 05:02:57',
                'updated_at' => '2021-07-07 05:02:57',
            ),
            79 => 
            array (
                'id' => 80,
                'idinforme' => '91',
                'url_informe' => 'https://uca.edu.sv/iudop/wp-content/uploads/informe91.pdf',
                'titulo' => 'Los salvadoreños evalúan la situación social y política del año 2011',
                'fecha_inicio' => '2001-09-20',
                'fecha_fin' => '2001-09-20',
                'tipo_informe' => 29,
                'eliminado' => 0,
                'idusuario' => NULL,
                'created_at' => '2021-07-07 05:02:57',
                'updated_at' => '2021-07-07 05:02:57',
            ),
            80 => 
            array (
                'id' => 81,
                'idinforme' => '92',
                'url_informe' => 'https://uca.edu.sv/iudop/wp-content/uploads/informe92.pdf',
                'titulo' => 'Los salvadoreños evalúan el primer año del Gobierno de Francisco Flores',
                'fecha_inicio' => '2002-05-18',
                'fecha_fin' => '2002-05-21',
                'tipo_informe' => 30,
                'eliminado' => 0,
                'idusuario' => NULL,
                'created_at' => '2021-07-07 05:02:57',
                'updated_at' => '2021-07-07 05:02:57',
            ),
            81 => 
            array (
                'id' => 82,
                'idinforme' => '93',
                'url_informe' => 'https://uca.edu.sv/iudop/wp-content/uploads/informe93_compressed.pdf',
                'titulo' => 'Encuesta de actitudes políticas y valores internacionales',
                'fecha_inicio' => '2002-04-06',
                'fecha_fin' => '2002-05-04',
                'tipo_informe' => 2,
                'eliminado' => 0,
                'idusuario' => NULL,
                'created_at' => '2021-07-07 05:02:57',
                'updated_at' => '2021-07-07 05:02:57',
            ),
            82 => 
            array (
                'id' => 83,
                'idinforme' => '94',
                'url_informe' => 'https://uca.edu.sv/iudop/wp-content/uploads/informe94.pdf',
                'titulo' => 'Los salvadoreños opinan sobre elproceso electoral de 2003',
                'fecha_inicio' => '2002-09-07',
                'fecha_fin' => '2002-09-11',
                'tipo_informe' => 4,
                'eliminado' => 0,
                'idusuario' => NULL,
                'created_at' => '2021-07-07 05:02:57',
                'updated_at' => '2021-07-07 05:02:57',
            ),
            83 => 
            array (
                'id' => 84,
                'idinforme' => '95',
                'url_informe' => 'https://uca.edu.sv/iudop/wp-content/uploads/informe95_compressed.pdf',
                'titulo' => 'Encuesta sobre clases medias y comportamiento político en El Salvador',
                'fecha_inicio' => '2002-11-01',
                'fecha_fin' => '2002-11-30',
                'tipo_informe' => 2,
                'eliminado' => 0,
                'idusuario' => NULL,
                'created_at' => '2021-07-07 05:02:57',
                'updated_at' => '2021-07-07 05:02:57',
            ),
            84 => 
            array (
                'id' => 85,
                'idinforme' => '96',
                'url_informe' => 'https://uca.edu.sv/iudop/wp-content/uploads/informe96.pdf',
                'titulo' => 'Encuesta sobre actitudes autoritarias en jóvenes residentes en la zona urbana del municipio de San Salvador',
                'fecha_inicio' => '2002-11-01',
                'fecha_fin' => '2002-11-01',
                'tipo_informe' => 2,
                'eliminado' => 0,
                'idusuario' => NULL,
                'created_at' => '2021-07-07 05:02:57',
                'updated_at' => '2021-07-07 05:02:57',
            ),
            85 => 
            array (
                'id' => 86,
                'idinforme' => '97',
                'url_informe' => 'https://uca.edu.sv/iudop/wp-content/uploads/informe97.pdf',
                'titulo' => 'Evaluación del país a finales de 2002 y perspectivas electorales para 2003',
                'fecha_inicio' => '2002-11-30',
                'fecha_fin' => '2002-12-08',
                'tipo_informe' => 31,
                'eliminado' => 0,
                'idusuario' => NULL,
                'created_at' => '2021-07-07 05:02:57',
                'updated_at' => '2021-07-07 05:02:57',
            ),
            86 => 
            array (
                'id' => 87,
                'idinforme' => '98',
                'url_informe' => 'https://uca.edu.sv/iudop/wp-content/uploads/informe-98-2.pdf',
                'titulo' => 'Los salvadoreños frente a las elecciones legislativas y municipales de 2003',
                'fecha_inicio' => '2003-02-08',
                'fecha_fin' => '2003-02-16',
                'tipo_informe' => 4,
                'eliminado' => 0,
                'idusuario' => NULL,
                'created_at' => '2021-07-07 05:02:57',
                'updated_at' => '2021-07-07 05:02:57',
            ),
            87 => 
            array (
                'id' => 88,
                'idinforme' => '99',
                'url_informe' => 'https://uca.edu.sv/iudop/wp-content/uploads/informe99-1.pdf',
                'titulo' => 'Encuesta sobre la jornada electoral del 16 de marzo de 2003',
                'fecha_inicio' => '2003-03-16',
                'fecha_fin' => '2003-03-16',
                'tipo_informe' => 18,
                'eliminado' => 0,
                'idusuario' => NULL,
                'created_at' => '2021-07-07 05:02:57',
                'updated_at' => '2021-07-07 05:02:57',
            ),
            88 => 
            array (
                'id' => 89,
                'idinforme' => '100',
                'url_informe' => 'https://uca.edu.sv/iudop/wp-content/uploads/informe100.pdf',
                'titulo' => 'Los salvadoreños evalúan el cuarto año del Gobierno de Francisco Flores',
                'fecha_inicio' => '2003-04-26',
                'fecha_fin' => '2003-05-09',
                'tipo_informe' => 32,
                'eliminado' => 0,
                'idusuario' => NULL,
                'created_at' => '2021-07-07 05:02:57',
                'updated_at' => '2021-07-07 05:02:57',
            ),
            89 => 
            array (
                'id' => 90,
                'idinforme' => '101',
                'url_informe' => 'https://uca.edu.sv/iudop/wp-content/uploads/informe101.pdf',
                'titulo' => 'Los salvadoreños frente a las elecciones presidenciales de 2004',
                'fecha_inicio' => '2003-10-03',
                'fecha_fin' => '2003-10-10',
                'tipo_informe' => 4,
                'eliminado' => 0,
                'idusuario' => NULL,
                'created_at' => '2021-07-07 05:02:57',
                'updated_at' => '2021-07-07 05:02:57',
            ),
            90 => 
            array (
                'id' => 91,
                'idinforme' => '102',
                'url_informe' => 'https://uca.edu.sv/iudop/wp-content/uploads/informe102.pdf',
                'titulo' => 'Evaluación del país a finales de 2003 y perspectivas electorales para 2004',
                'fecha_inicio' => '2003-11-29',
                'fecha_fin' => '2003-12-07',
                'tipo_informe' => 33,
                'eliminado' => 0,
                'idusuario' => NULL,
                'created_at' => '2021-07-07 05:02:57',
                'updated_at' => '2021-07-07 05:02:57',
            ),
            91 => 
            array (
                'id' => 92,
                'idinforme' => '103',
                'url_informe' => 'https://uca.edu.sv/iudop/wp-content/uploads/informe103.pdf',
                'titulo' => 'Los salvadoreños frente a las elecciones presidenciales de 2004',
                'fecha_inicio' => '2004-02-14',
                'fecha_fin' => '2004-02-22',
                'tipo_informe' => 5,
                'eliminado' => 0,
                'idusuario' => NULL,
                'created_at' => '2021-07-07 05:02:57',
                'updated_at' => '2021-07-07 05:02:57',
            ),
            92 => 
            array (
                'id' => 93,
                'idinforme' => '104',
                'url_informe' => 'https://uca.edu.sv/iudop/wp-content/uploads/informe104-1.pdf',
                'titulo' => 'Encuesta sobre la jornada electoral del 21 de marzo de 2004',
                'fecha_inicio' => '2004-03-21',
                'fecha_fin' => '2004-03-21',
                'tipo_informe' => 18,
                'eliminado' => 0,
                'idusuario' => NULL,
                'created_at' => '2021-07-07 05:02:57',
                'updated_at' => '2021-07-07 05:02:57',
            ),
            93 => 
            array (
                'id' => 94,
                'idinforme' => '105',
                'url_informe' => 'https://uca.edu.sv/iudop/wp-content/uploads/informe105.pdf',
                'titulo' => 'Evaluación de los salvadoreños sobre el Gobierno de Francisco Flores y expectativas hacia el nuevo Gobierno',
                'fecha_inicio' => '2004-05-19',
                'fecha_fin' => '2004-05-26',
                'tipo_informe' => 34,
                'eliminado' => 0,
                'idusuario' => NULL,
                'created_at' => '2021-07-07 05:02:57',
                'updated_at' => '2021-07-07 05:02:57',
            ),
            94 => 
            array (
                'id' => 95,
                'idinforme' => '106',
                'url_informe' => 'https://uca.edu.sv/iudop/wp-content/uploads/informe106.pdf',
                'titulo' => 'Los salvadoreños evalúan los cien días de Gobierno de Antonio Saca',
                'fecha_inicio' => '2004-08-27',
                'fecha_fin' => '2004-09-01',
                'tipo_informe' => 35,
                'eliminado' => 0,
                'idusuario' => NULL,
                'created_at' => '2021-07-07 05:02:57',
                'updated_at' => '2021-07-07 05:02:57',
            ),
            95 => 
            array (
                'id' => 96,
                'idinforme' => '107',
                'url_informe' => 'https://uca.edu.sv/iudop/wp-content/uploads/informe107.pdf',
                'titulo' => 'Los salvadoreños evalúan la situación del país a finales de 2004',
                'fecha_inicio' => '2004-11-21',
                'fecha_fin' => '2004-11-28',
                'tipo_informe' => 36,
                'eliminado' => 0,
                'idusuario' => NULL,
                'created_at' => '2021-07-07 05:02:57',
                'updated_at' => '2021-07-07 05:02:57',
            ),
            96 => 
            array (
                'id' => 97,
                'idinforme' => '108',
                'url_informe' => 'https://uca.edu.sv/iudop/wp-content/uploads/informe108.pdf',
                'titulo' => 'Los salvadoreños evalúan el primer año de Gobierno de Antonio Saca',
                'fecha_inicio' => '2005-05-07',
                'fecha_fin' => '2005-05-15',
                'tipo_informe' => 37,
                'eliminado' => 0,
                'idusuario' => NULL,
                'created_at' => '2021-07-07 05:02:57',
                'updated_at' => '2021-07-07 05:02:57',
            ),
            97 => 
            array (
                'id' => 98,
                'idinforme' => '109',
                'url_informe' => 'https://uca.edu.sv/iudop/wp-content/uploads/informe109.pdf',
                'titulo' => 'Los salvadoreños evalúan la situación del país a finales de 2005 y opinan sobre las elecciones de 2006',
                'fecha_inicio' => '2005-11-11',
                'fecha_fin' => '2005-11-20',
                'tipo_informe' => 38,
                'eliminado' => 0,
                'idusuario' => NULL,
                'created_at' => '2021-07-07 05:02:57',
                'updated_at' => '2021-07-07 05:02:57',
            ),
            98 => 
            array (
                'id' => 99,
                'idinforme' => '110',
                'url_informe' => 'https://uca.edu.sv/iudop/wp-content/uploads/informe110.pdf',
                'titulo' => 'Los salvadoreños frente a las elecciones legislativas y municipales de 2006',
                'fecha_inicio' => '2006-02-04',
                'fecha_fin' => '2006-02-14',
                'tipo_informe' => 4,
                'eliminado' => 0,
                'idusuario' => NULL,
                'created_at' => '2021-07-07 05:02:57',
                'updated_at' => '2021-07-07 05:02:57',
            ),
            99 => 
            array (
                'id' => 100,
                'idinforme' => '111',
                'url_informe' => 'https://uca.edu.sv/iudop/wp-content/uploads/informe111.pdf',
                'titulo' => 'Los salvadoreños evalúan el segundo año de Gobierno de Antonio Saca',
                'fecha_inicio' => '2006-05-07',
                'fecha_fin' => '2006-05-14',
                'tipo_informe' => 39,
                'eliminado' => 0,
                'idusuario' => NULL,
                'created_at' => '2021-07-07 05:02:57',
                'updated_at' => '2021-07-07 05:02:57',
            ),
            100 => 
            array (
                'id' => 101,
                'idinforme' => '112',
                'url_informe' => 'https://uca.edu.sv/iudop/wp-content/uploads/informe112.pdf',
                'titulo' => 'Evaluación del país a finales del 2006 y perspectivas para 2007',
                'fecha_inicio' => '2006-11-04',
                'fecha_fin' => '2006-11-12',
                'tipo_informe' => 40,
                'eliminado' => 0,
                'idusuario' => NULL,
                'created_at' => '2021-07-07 05:02:57',
                'updated_at' => '2021-07-07 05:02:57',
            ),
            101 => 
            array (
                'id' => 102,
                'idinforme' => '113',
                'url_informe' => 'https://uca.edu.sv/iudop/wp-content/uploads/Informe113.pdf',
                'titulo' => 'Los salvadoreños y salvadoreñas evalúan el tercer año de Gobierno de Antonio Saca',
                'fecha_inicio' => '2007-04-29',
                'fecha_fin' => '2007-05-08',
                'tipo_informe' => 41,
                'eliminado' => 0,
                'idusuario' => NULL,
                'created_at' => '2021-07-07 05:02:57',
                'updated_at' => '2021-07-07 05:02:57',
            ),
            102 => 
            array (
                'id' => 103,
                'idinforme' => '114',
                'url_informe' => 'https://uca.edu.sv/iudop/wp-content/uploads/Informe114.pdf',
                'titulo' => 'Los salvadoreños y salvadoreñas evalúan la situación del país a finales de 2007',
                'fecha_inicio' => '2007-10-26',
                'fecha_fin' => '2007-11-06',
                'tipo_informe' => 42,
                'eliminado' => 0,
                'idusuario' => NULL,
                'created_at' => '2021-07-07 05:02:57',
                'updated_at' => '2021-07-07 05:02:57',
            ),
            103 => 
            array (
                'id' => 104,
                'idinforme' => '115',
                'url_informe' => 'https://uca.edu.sv/iudop/wp-content/uploads/finalmineria040208-1.pdf',
                'titulo' => 'Conocimientos y percepciones hacia la minería en zonas afectadas por la incursión minera',
                'fecha_inicio' => '2007-09-29',
                'fecha_fin' => '2007-10-10',
                'tipo_informe' => 2,
                'eliminado' => 0,
                'idusuario' => NULL,
                'created_at' => '2021-07-07 05:02:57',
                'updated_at' => '2021-07-07 05:02:57',
            ),
            104 => 
            array (
                'id' => 105,
                'idinforme' => '116',
                'url_informe' => 'https://uca.edu.sv/iudop/wp-content/uploads/Informe116.pdf',
                'titulo' => 'Los salvadoreños evalúan el cuarto año de Gobierno de Antonio Saca y opinan sobre la coyuntura política electoral',
                'fecha_inicio' => '2008-05-03',
                'fecha_fin' => '2008-05-12',
                'tipo_informe' => 43,
                'eliminado' => 0,
                'idusuario' => NULL,
                'created_at' => '2021-07-07 05:02:57',
                'updated_at' => '2021-07-07 05:02:57',
            ),
            105 => 
            array (
                'id' => 106,
                'idinforme' => '117',
                'url_informe' => 'https://uca.edu.sv/iudop/wp-content/uploads/informe117.pdf',
                'titulo' => 'Los salvadoreños y salvadoreñas opinan sobre el proceso electoral de 2009',
                'fecha_inicio' => '2008-09-01',
                'fecha_fin' => '2008-09-01',
                'tipo_informe' => 5,
                'eliminado' => 0,
                'idusuario' => NULL,
                'created_at' => '2021-07-07 05:02:57',
                'updated_at' => '2021-07-07 05:02:57',
            ),
            106 => 
            array (
                'id' => 107,
                'idinforme' => '118',
                'url_informe' => 'https://uca.edu.sv/iudop/wp-content/uploads/informe118_e.pdf',
                'titulo' => 'Los salvadoreños y salvadoreñas evalúan la situación del país a finales de 2008 y opinan sobre las elecciones legislativas y municipales de 2009',
                'fecha_inicio' => '2008-11-01',
                'fecha_fin' => '2008-11-01',
                'tipo_informe' => 44,
                'eliminado' => 0,
                'idusuario' => NULL,
                'created_at' => '2021-07-07 05:02:57',
                'updated_at' => '2021-07-07 05:02:57',
            ),
            107 => 
            array (
                'id' => 108,
                'idinforme' => '119',
                'url_informe' => 'https://uca.edu.sv/iudop/wp-content/uploads/informe119.pdf',
                'titulo' => 'Los salvadoreños y salvadoreñas frente a las elecciones presidenciales de 2009',
                'fecha_inicio' => '2009-02-01',
                'fecha_fin' => '2009-02-28',
                'tipo_informe' => 4,
                'eliminado' => 0,
                'idusuario' => NULL,
                'created_at' => '2021-07-07 05:02:57',
                'updated_at' => '2021-07-07 05:02:57',
            ),
            108 => 
            array (
                'id' => 109,
                'idinforme' => '120',
                'url_informe' => 'https://uca.edu.sv/iudop/wp-content/uploads/informe120.pdf',
                'titulo' => 'Evaluación de los salvadoreños y salvadoreñas del Gobierno de Antonio Saca y expectativas hacia el nuevo Gobierno',
                'fecha_inicio' => '2009-04-01',
                'fecha_fin' => '2009-05-31',
                'tipo_informe' => 45,
                'eliminado' => 0,
                'idusuario' => NULL,
                'created_at' => '2021-07-07 05:02:57',
                'updated_at' => '2021-07-07 05:02:57',
            ),
            109 => 
            array (
                'id' => 110,
                'idinforme' => '121',
                'url_informe' => 'https://uca.edu.sv/iudop/wp-content/uploads/informe121.pdf',
                'titulo' => 'Los salvadoreños y salvadoreñas evalúan los cien días de Gobierno de Mauricio Funes',
                'fecha_inicio' => '2009-08-01',
                'fecha_fin' => '2009-08-31',
                'tipo_informe' => 46,
                'eliminado' => 0,
                'idusuario' => NULL,
                'created_at' => '2021-07-07 05:02:57',
                'updated_at' => '2021-07-07 05:02:57',
            ),
            110 => 
            array (
                'id' => 111,
                'idinforme' => '122',
                'url_informe' => 'https://uca.edu.sv/iudop/wp-content/uploads/informe122.pdf',
                'titulo' => 'La religión para las y los salvadoreños',
                'fecha_inicio' => '2009-06-01',
                'fecha_fin' => '2009-06-30',
                'tipo_informe' => 2,
                'eliminado' => 0,
                'idusuario' => NULL,
                'created_at' => '2021-07-07 05:02:57',
                'updated_at' => '2021-07-07 05:02:57',
            ),
            111 => 
            array (
                'id' => 112,
                'idinforme' => '123',
                'url_informe' => 'https://uca.edu.sv/iudop/wp-content/uploads/informe123.pdf',
                'titulo' => 'La victimización y la percepción de inseguridad en El Salvador en 2009',
                'fecha_inicio' => '2009-07-01',
                'fecha_fin' => '2009-08-01',
                'tipo_informe' => 2,
                'eliminado' => 0,
                'idusuario' => NULL,
                'created_at' => '2021-07-07 05:02:57',
                'updated_at' => '2021-07-07 05:02:57',
            ),
            112 => 
            array (
                'id' => 113,
                'idinforme' => '124',
                'url_informe' => 'https://uca.edu.sv/iudop/wp-content/uploads/informe124.pdf',
                'titulo' => 'Los salvadoreños y salvadoreñas evalúan la situación del país a finales de 2009',
                'fecha_inicio' => '2009-11-01',
                'fecha_fin' => '2009-11-30',
                'tipo_informe' => 47,
                'eliminado' => 0,
                'idusuario' => NULL,
                'created_at' => '2021-07-07 05:02:57',
                'updated_at' => '2021-07-07 05:02:57',
            ),
            113 => 
            array (
                'id' => 114,
                'idinforme' => '125',
                'url_informe' => 'https://uca.edu.sv/iudop/wp-content/uploads/informe125.pdf',
                'titulo' => 'Los salvadoreños y salvadoreñas evalúan el primer año de Gobierno de Mauricio Funes',
                'fecha_inicio' => '2010-05-01',
                'fecha_fin' => '2010-05-30',
                'tipo_informe' => 48,
                'eliminado' => 0,
                'idusuario' => NULL,
                'created_at' => '2021-07-07 05:02:57',
                'updated_at' => '2021-07-07 05:02:57',
            ),
            114 => 
            array (
                'id' => 115,
                'idinforme' => '126',
                'url_informe' => 'https://uca.edu.sv/iudop/wp-content/uploads/informeval126.pdf',
                'titulo' => 'Los salvadoreños y salvadoreñas evalúan la situación del país en 2010',
                'fecha_inicio' => '2010-11-01',
                'fecha_fin' => '2010-11-30',
                'tipo_informe' => 49,
                'eliminado' => 0,
                'idusuario' => NULL,
                'created_at' => '2021-07-07 05:02:57',
                'updated_at' => '2021-07-07 05:02:57',
            ),
            115 => 
            array (
                'id' => 116,
                'idinforme' => '127',
                'url_informe' => 'https://uca.edu.sv/iudop/wp-content/uploads/informe127.pdf',
                'titulo' => 'Los salvadoreños y salvadoreñas evalúan el segundo año de Gobierno de Mauricio Funes',
                'fecha_inicio' => '2011-04-01',
                'fecha_fin' => '2011-05-01',
                'tipo_informe' => 50,
                'eliminado' => 0,
                'idusuario' => NULL,
                'created_at' => '2021-07-07 05:02:57',
                'updated_at' => '2021-07-07 05:02:57',
            ),
            116 => 
            array (
                'id' => 117,
                'idinforme' => '128',
                'url_informe' => 'https://uca.edu.sv/iudop/wp-content/uploads/informe128.pdf',
                'titulo' => 'Los salvadoreños y salvadoreñas evalúan la situación del país a finales de 2011 y opinan sobre las elecciones de 2012',
                'fecha_inicio' => '2011-11-01',
                'fecha_fin' => '2011-12-01',
                'tipo_informe' => 51,
                'eliminado' => 0,
                'idusuario' => NULL,
                'created_at' => '2021-07-07 05:02:57',
                'updated_at' => '2021-07-07 05:02:57',
            ),
            117 => 
            array (
                'id' => 118,
                'idinforme' => '129',
                'url_informe' => 'https://uca.edu.sv/iudop/wp-content/uploads/informe129.pdf',
                'titulo' => 'Los salvadoreños y salvadoreñas frente a las elecciones legislativas y municipales de 2012',
                'fecha_inicio' => '2012-02-01',
                'fecha_fin' => '2012-02-01',
                'tipo_informe' => 4,
                'eliminado' => 0,
                'idusuario' => NULL,
                'created_at' => '2021-07-07 05:02:57',
                'updated_at' => '2021-07-07 05:02:57',
            ),
            118 => 
            array (
                'id' => 119,
                'idinforme' => '130',
                'url_informe' => 'https://uca.edu.sv/iudop/wp-content/uploads/informe130.pdf',
                'titulo' => 'Los salvadoreños y salvadoreñas evalúan el tercer año de Gobierno de Mauricio Funes y opinan sobre el proceso electoral de 2012',
                'fecha_inicio' => '2012-04-01',
                'fecha_fin' => '2012-05-31',
                'tipo_informe' => 52,
                'eliminado' => 0,
                'idusuario' => NULL,
                'created_at' => '2021-07-07 05:02:57',
                'updated_at' => '2021-07-07 05:02:57',
            ),
            119 => 
            array (
                'id' => 120,
                'idinforme' => '131',
                'url_informe' => 'https://uca.edu.sv/iudop/wp-content/uploads/informe131.pdf',
                'titulo' => 'Los salvadoreños y salvadoreñas evalúan la situación del país a finales de 2012',
                'fecha_inicio' => '2012-11-01',
                'fecha_fin' => '2012-11-01',
                'tipo_informe' => 53,
                'eliminado' => 0,
                'idusuario' => NULL,
                'created_at' => '2021-07-07 05:02:57',
                'updated_at' => '2021-07-07 05:02:57',
            ),
            120 => 
            array (
                'id' => 121,
                'idinforme' => '132',
                'url_informe' => 'https://uca.edu.sv/iudop/wp-content/uploads/informe132.pdf',
                'titulo' => 'Los salvadoreños y salvadoreñas evalúan el cuarto año de Gobierno de Mauricio Funes',
                'fecha_inicio' => '2013-05-01',
                'fecha_fin' => '2013-05-31',
                'tipo_informe' => 54,
                'eliminado' => 0,
                'idusuario' => NULL,
                'created_at' => '2021-07-07 05:02:57',
                'updated_at' => '2021-07-07 05:02:57',
            ),
            121 => 
            array (
                'id' => 122,
                'idinforme' => '133',
                'url_informe' => 'https://uca.edu.sv/iudop/wp-content/uploads/INFORME-133-1.pdf',
                'titulo' => 'Los salvadoreños y salvadoreñas evalúan la situación del país a finales de 2013 y opinan sobre la elecciones presidenciales de 2014',
                'fecha_inicio' => '2013-11-01',
                'fecha_fin' => '2013-11-30',
                'tipo_informe' => 55,
                'eliminado' => 0,
                'idusuario' => NULL,
                'created_at' => '2021-07-07 05:02:57',
                'updated_at' => '2021-07-07 05:02:57',
            ),
            122 => 
            array (
                'id' => 123,
                'idinforme' => '134',
                'url_informe' => 'https://uca.edu.sv/iudop/wp-content/uploads/INF134-1.pdf',
                'titulo' => 'Los salvadoreños y salvadoreñas frente a las elecciones presidenciales de 2014',
                'fecha_inicio' => '2014-01-01',
                'fecha_fin' => '2014-01-31',
                'tipo_informe' => 4,
                'eliminado' => 0,
                'idusuario' => NULL,
                'created_at' => '2021-07-07 05:02:57',
                'updated_at' => '2021-07-07 05:02:57',
            ),
            123 => 
            array (
                'id' => 124,
                'idinforme' => '135',
                'url_informe' => 'https://uca.edu.sv/iudop/wp-content/uploads/INFORME-135-1.pdf',
                'titulo' => 'Los salvadoreños y salvadoreñas frente a la segunda ronda de elección presidencial 2014',
                'fecha_inicio' => '2014-02-01',
                'fecha_fin' => '2014-02-28',
                'tipo_informe' => 4,
                'eliminado' => 0,
                'idusuario' => NULL,
                'created_at' => '2021-07-07 05:02:57',
                'updated_at' => '2021-07-07 05:02:57',
            ),
            124 => 
            array (
                'id' => 125,
                'idinforme' => '136',
                'url_informe' => 'https://uca.edu.sv/iudop/wp-content/uploads/INFORME-136-1.pdf',
                'titulo' => 'Los salvadoreños y salvadoreñas evalúan al Gobierno de Mauricio Funes y el pasado proceso electoral',
                'fecha_inicio' => '2014-05-01',
                'fecha_fin' => '2014-05-31',
                'tipo_informe' => 56,
                'eliminado' => 0,
                'idusuario' => NULL,
                'created_at' => '2021-07-07 05:02:58',
                'updated_at' => '2021-07-07 05:02:58',
            ),
            125 => 
            array (
                'id' => 126,
                'idinforme' => '137',
                'url_informe' => 'https://uca.edu.sv/iudop/wp-content/uploads/INFORME-137-1.pdf',
                'titulo' => 'Evaluación del país a finales de 2014',
                'fecha_inicio' => '2014-11-01',
                'fecha_fin' => '2014-11-30',
                'tipo_informe' => 57,
                'eliminado' => 0,
                'idusuario' => NULL,
                'created_at' => '2021-07-07 05:02:58',
                'updated_at' => '2021-07-07 05:02:58',
            ),
            126 => 
            array (
                'id' => 127,
                'idinforme' => '139',
                'url_informe' => 'https://uca.edu.sv/iudop/wp-content/uploads/INFORME139-1.pdf',
                'titulo' => 'Los salvadoreños y salvadoreñas evalúan la situación del país a finales de 2015',
                'fecha_inicio' => '2015-11-01',
                'fecha_fin' => '2015-12-31',
                'tipo_informe' => 58,
                'eliminado' => 0,
                'idusuario' => NULL,
                'created_at' => '2021-07-07 05:02:58',
                'updated_at' => '2021-07-07 05:02:58',
            ),
            127 => 
            array (
                'id' => 128,
                'idinforme' => '140',
                'url_informe' => 'https://uca.edu.sv/iudop/wp-content/uploads/INFORME-140.pdf',
                'titulo' => 'Los salvadoreños y salvadoreñas evalúan el segundo año de Gobierno de Salvador Sánchez Cerén',
                'fecha_inicio' => '2016-06-01',
                'fecha_fin' => '2016-07-31',
                'tipo_informe' => 59,
                'eliminado' => 0,
                'idusuario' => NULL,
                'created_at' => '2021-07-07 05:02:58',
                'updated_at' => '2021-07-07 05:02:58',
            ),
            128 => 
            array (
                'id' => 129,
                'idinforme' => '141',
                'url_informe' => 'https://uca.edu.sv/iudop/wp-content/uploads/INFORME-141-1.pdf',
                'titulo' => 'Los salvadoreños evalúan la situación del país a finales de 2016',
                'fecha_inicio' => '2016-11-01',
                'fecha_fin' => '2016-11-30',
                'tipo_informe' => 60,
                'eliminado' => 0,
                'idusuario' => NULL,
                'created_at' => '2021-07-07 05:02:58',
                'updated_at' => '2021-07-07 05:02:58',
            ),
            129 => 
            array (
                'id' => 130,
                'idinforme' => '142',
                'url_informe' => 'https://uca.edu.sv/iudop/wp-content/uploads/INFORME-142-1.pdf',
                'titulo' => 'Los salvadoreños evalúan el tercer año de Gobierno de Salvador Sánchez Cerén',
                'fecha_inicio' => '2017-05-01',
                'fecha_fin' => '2017-05-31',
                'tipo_informe' => 61,
                'eliminado' => 0,
                'idusuario' => NULL,
                'created_at' => '2021-07-07 05:02:58',
                'updated_at' => '2021-07-07 05:02:58',
            ),
            130 => 
            array (
                'id' => 131,
                'idinforme' => '143',
                'url_informe' => 'https://uca.edu.sv/iudop/wp-content/uploads/INFORME-143-1.pdf',
                'titulo' => 'Evaluación del país a finales de 2017 y perspectivas electorales para 2018',
                'fecha_inicio' => '2017-11-01',
                'fecha_fin' => '2017-11-30',
                'tipo_informe' => 62,
                'eliminado' => 0,
                'idusuario' => NULL,
                'created_at' => '2021-07-07 05:02:58',
                'updated_at' => '2021-07-07 05:02:58',
            ),
            131 => 
            array (
                'id' => 132,
                'idinforme' => '144',
                'url_informe' => 'https://uca.edu.sv/iudop/wp-content/uploads/INFORME-144-1.pdf',
                'titulo' => 'Los salvadoreños opinan sobre las elecciones legislativas y municipales de 2018',
                'fecha_inicio' => '2018-01-01',
                'fecha_fin' => '2018-02-01',
                'tipo_informe' => 63,
                'eliminado' => 0,
                'idusuario' => NULL,
                'created_at' => '2021-07-07 05:02:58',
                'updated_at' => '2021-07-07 05:02:58',
            ),
            132 => 
            array (
                'id' => 133,
                'idinforme' => '145',
                'url_informe' => 'https://uca.edu.sv/iudop/wp-content/uploads/INFORME-145-1.pdf',
                'titulo' => 'Los salvadoreños evalúan el cuarto año de Gobierno de Salvador Sánchez Cerén y opinan sobre el pasado proceso electoral',
                'fecha_inicio' => '2018-04-01',
                'fecha_fin' => '2018-05-01',
                'tipo_informe' => 64,
                'eliminado' => 0,
                'idusuario' => NULL,
                'created_at' => '2021-07-07 05:02:58',
                'updated_at' => '2021-07-07 05:02:58',
            ),
            133 => 
            array (
                'id' => 134,
                'idinforme' => '146',
                'url_informe' => 'https://uca.edu.sv/iudop/wp-content/uploads/Boletin-4_2018.pdf',
                'titulo' => 'Los salvadoreños y salvadoreñas evalúan la situación del país a finales de 2018 y opinan sobre las elecciones presidenciales de 2019',
                'fecha_inicio' => '2018-12-01',
                'fecha_fin' => '2018-12-01',
                'tipo_informe' => 65,
                'eliminado' => 0,
                'idusuario' => NULL,
                'created_at' => '2021-07-07 05:02:58',
                'updated_at' => '2021-07-07 05:02:58',
            ),
            134 => 
            array (
                'id' => 135,
                'idinforme' => '147',
                'url_informe' => 'https://uca.edu.sv/iudop/wp-content/uploads/INFORME-CRISTOSAL-COMPLETO-1.pdf',
                'titulo' => 'Los salvadoreños y salvadoreñas opinan sobre el desplazamiento interno forzado por violencia y las medidas extraordinarias',
                'fecha_inicio' => '2018-11-16',
                'fecha_fin' => '2018-12-02',
                'tipo_informe' => 2,
                'eliminado' => 0,
                'idusuario' => NULL,
                'created_at' => '2021-07-07 05:02:58',
                'updated_at' => '2021-07-07 05:02:58',
            ),
            135 => 
            array (
                'id' => 136,
                'idinforme' => '148',
                'url_informe' => 'https://uca.edu.sv/iudop/wp-content/uploads/Boletin-de-prensa_final-7-05-19.pdf',
                'titulo' => 'Los salvadoreños y salvadoreñas evalúan las elecciones presidenciales del 3 de febrero de 2019',
                'fecha_inicio' => '2019-03-16',
                'fecha_fin' => '2019-03-26',
                'tipo_informe' => 5,
                'eliminado' => 0,
                'idusuario' => NULL,
                'created_at' => '2021-07-07 05:02:58',
                'updated_at' => '2021-07-07 05:02:58',
            ),
            136 => 
            array (
                'id' => 137,
                'idinforme' => '149',
                'url_informe' => 'https://uca.edu.sv/iudop/wp-content/uploads/evagob2019boletin.pdf',
                'titulo' => 'Los salvadoreños evalúan el Gobierno de Salvador Sánchez Cerén y demás Órganos del Estado salvadoreño',
                'fecha_inicio' => '2019-04-27',
                'fecha_fin' => '2019-05-07',
                'tipo_informe' => 66,
                'eliminado' => 0,
                'idusuario' => NULL,
                'created_at' => '2021-07-07 05:02:58',
                'updated_at' => '2021-07-07 05:02:58',
            ),
            137 => 
            array (
                'id' => 138,
                'idinforme' => '150',
                'url_informe' => 'https://uca.edu.sv/iudop/wp-content/uploads/Seattle_Vesion_01112019_ESPFinal.pdf',
                'titulo' => 'Estado de la situación general del país desde la opinión pública salvadoreña. La percepción de la población salvadoreña sobre la economía, la educación, la salud, la seguridad y la justicia y su opinión de cara al futuro del país',
                'fecha_inicio' => '2019-06-08',
                'fecha_fin' => '2019-06-30',
                'tipo_informe' => 8,
                'eliminado' => 0,
                'idusuario' => NULL,
                'created_at' => '2021-07-07 05:02:58',
                'updated_at' => '2021-07-07 05:02:58',
            ),
            138 => 
            array (
                'id' => 139,
                'idinforme' => '151',
                'url_informe' => 'https://uca.edu.sv/iudop/wp-content/uploads/Boletin-100NB_final.pdf.pdf',
                'titulo' => 'Los salvadoreños y salvadoreñas evalúan los primeros cien días de Gobierno del presidente Nayib Bukele',
                'fecha_inicio' => '2019-08-31',
                'fecha_fin' => '2019-09-08',
                'tipo_informe' => 67,
                'eliminado' => 0,
                'idusuario' => NULL,
                'created_at' => '2021-07-07 05:02:58',
                'updated_at' => '2021-07-07 05:02:58',
            ),
            139 => 
            array (
                'id' => 140,
                'idinforme' => '152',
                'url_informe' => 'https://uca.edu.sv/iudop/wp-content/uploads/BOLEVAL2019-1.pdf',
                'titulo' => 'La población salvadoreña evalúa la situación general del país a finales del año 2019',
                'fecha_inicio' => '2019-11-22',
                'fecha_fin' => '2019-12-03',
                'tipo_informe' => 68,
                'eliminado' => 0,
                'idusuario' => NULL,
                'created_at' => '2021-07-07 05:02:58',
                'updated_at' => '2021-07-07 05:02:58',
            ),
            140 => 
            array (
                'id' => 141,
                'idinforme' => '153',
                'url_informe' => 'https://uca.edu.sv/iudop/wp-content/uploads/BOLETI%CC%81N_AA-1.pdf',
                'titulo' => 'Las salvadoreñas y salvadoreños evalúan los Acuerdos de paz a 28 años de su firma y opinan sobre la democracia en el país',
                'fecha_inicio' => '2019-11-22',
                'fecha_fin' => '2019-12-03',
                'tipo_informe' => 1,
                'eliminado' => 0,
                'idusuario' => NULL,
                'created_at' => '2021-07-07 05:02:58',
                'updated_at' => '2021-07-07 05:02:58',
            ),
            141 => 
            array (
                'id' => 142,
                'idinforme' => '154',
                'url_informe' => 'https://uca.edu.sv/iudop/publicacion/encuesta-especializada-31/',
                'titulo' => 'La población salvadoreña opina sobre el derecho humano al agua',
                'fecha_inicio' => '2020-01-25',
                'fecha_fin' => '2020-02-05',
                'tipo_informe' => 2,
                'eliminado' => 0,
                'idusuario' => NULL,
                'created_at' => '2021-07-07 05:02:58',
                'updated_at' => '2021-07-07 05:02:58',
            ),
            142 => 
            array (
                'id' => 143,
                'idinforme' => '155',
                'url_informe' => 'https://uca.edu.sv/iudop/wp-content/uploads/INFORME_COVID19-2.pdf',
                'titulo' => 'Sondeo de opinión sobre las medidas que las autoridades han tomado en los centros de contención en cuarentena durante la emergencia nacional por COVID-19',
                'fecha_inicio' => '2020-05-01',
                'fecha_fin' => '2020-05-01',
                'tipo_informe' => 69,
                'eliminado' => 0,
                'idusuario' => NULL,
                'created_at' => '2021-07-07 05:02:58',
                'updated_at' => '2021-07-07 05:02:58',
            ),
            143 => 
            array (
                'id' => 144,
                'idinforme' => '156',
                'url_informe' => 'https://uca.edu.sv/iudop/wp-content/uploads/BOLETIN-PRE-ELECTORAL-NOVIEMBRE-2020-08122020.pdf',
                'titulo' => 'La población salvadoreña opina sobre el proceso electoral de 2021',
                'fecha_inicio' => '2020-11-10',
                'fecha_fin' => '2020-11-24',
                'tipo_informe' => 4,
                'eliminado' => 0,
                'idusuario' => NULL,
                'created_at' => '2021-07-07 05:02:58',
                'updated_at' => '2021-07-07 05:02:58',
            ),
            144 => 
            array (
                'id' => 145,
                'idinforme' => '157',
                'url_informe' => 'https://uca.edu.sv/iudop/wp-content/uploads/informe156-1.pdf',
                'titulo' => 'Sondeo de opinión sobre el primer año del Gobierno del Presidente Nayib Bukele y el manejo de la pandemia de COVID-19 por parte de las autoridades',
                'fecha_inicio' => '2020-06-06',
                'fecha_fin' => '2020-06-13',
                'tipo_informe' => 70,
                'eliminado' => 0,
                'idusuario' => NULL,
                'created_at' => '2021-07-07 05:02:58',
                'updated_at' => '2021-07-07 05:02:58',
            ),
            145 => 
            array (
                'id' => 146,
                'idinforme' => '158',
                'url_informe' => 'https://uca.edu.sv/iudop/wp-content/uploads/Boletin-Preelectoral-SAN-SALVADOR.pdf',
                'titulo' => 'Los capitalinos opinan sobre la elección para la alcaldía del municipio de San Salvador',
                'fecha_inicio' => '2020-12-06',
                'fecha_fin' => '2020-12-15',
                'tipo_informe' => 71,
                'eliminado' => 0,
                'idusuario' => NULL,
                'created_at' => '2021-07-07 05:02:58',
                'updated_at' => '2021-07-07 05:02:58',
            ),
            146 => 
            array (
                'id' => 147,
                'idinforme' => '159',
                'url_informe' => 'https://uca.edu.sv/iudop/wp-content/uploads/BOLETIN-EV-ANO-2020-Nacional.pdf',
                'titulo' => 'La población salvadoreña evalúa la situación del país a finales del año 2020_x000D_
',
                'fecha_inicio' => '2020-12-06',
                'fecha_fin' => '2020-12-15',
                'tipo_informe' => 72,
                'eliminado' => 0,
                'idusuario' => NULL,
                'created_at' => '2021-07-07 05:02:58',
                'updated_at' => '2021-07-07 05:02:58',
            ),
            147 => 
            array (
                'id' => 148,
                'idinforme' => '160',
                'url_informe' => 'https://uca.edu.sv/iudop/wp-content/uploads/Boletin-Preelectoral-enero-febrero-2021.pdf',
                'titulo' => 'La población salvadoreña de cara a las elecciones del 28 de febrero de 2021',
                'fecha_inicio' => '2021-01-15',
                'fecha_fin' => '2021-02-03',
                'tipo_informe' => 4,
                'eliminado' => 0,
                'idusuario' => NULL,
                'created_at' => '2021-07-07 05:02:58',
                'updated_at' => '2021-07-07 05:02:58',
            ),
            148 => 
            array (
                'id' => 149,
                'idinforme' => '161',
                'url_informe' => 'https://uca.edu.sv/iudop/wp-content/uploads/Boletin-de-Eva.-de-Gobierno-del-2do-ano-de-NB.pdf',
                'titulo' => 'La población salvadoreña evalúa el segundo año de Gobierno del presidente Nayib Bukele',
                'fecha_inicio' => '2021-05-15',
                'fecha_fin' => '2021-05-21',
                'tipo_informe' => 73,
                'eliminado' => 0,
                'idusuario' => NULL,
                'created_at' => '2021-07-07 05:02:58',
                'updated_at' => '2021-07-07 05:02:58',
            ),
        ));
        
        
    }
}